(function () {
  const posts = [
    { id: 1, name: "Carlos Ramírez", initials: "CR", time: "Hace 2 horas", title: "¿Cuáles son las ventajas clave de nuestra tecnología HDR en comparación con modelos anteriores?", category: "Dudas de Producto", replies: [] },
    { id: 2, name: "Laura Méndez", initials: "LM", time: "Hace 5 horas", title: "¿Alguien puede compartir consejos para explicar mejor el control por voz a los clientes?", category: "Ventas y Argumentos", replies: [] },
    { id: 3, name: "Juan Pérez", initials: "JP", time: "Hace 1 día", title: "¿Cómo manejo las objeciones de los clientes sobre el precio?", category: "Consultas Generales", replies: [] }
  ];
  let activeReply = null;
  const $ = (s) => document.querySelector(s);
  const esc = (v) => String(v).replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
  function toast(message) {
    let node = $("#learningToast");
    if (!node) { node = document.createElement("div"); node.id = "learningToast"; node.className = "learning-toast-v3"; document.body.appendChild(node); }
    node.textContent = message; node.classList.add("is-visible"); clearTimeout(node._timer); node._timer = setTimeout(() => node.classList.remove("is-visible"), 2600);
  }
  function renderPosts() {
    const list = $("#postList"); if (!list) return;
    list.innerHTML = posts.length ? posts.map((post) => `<article class="learning-post-v3"><div class="learning-post-top"><span class="learning-post-avatar">${esc(post.initials)}</span><strong>${esc(post.name)}</strong><time>${esc(post.time)}</time></div><p>${esc(post.title)}</p><span class="learning-post-category">${esc(post.category)}</span><button class="learning-reply-button" data-reply="${post.id}" type="button">Responder</button>${activeReply === post.id ? `<div class="learning-reply-box"><textarea data-reply-input="${post.id}" placeholder="Escribe tu respuesta..."></textarea><div><button class="learning-cancel-reply" data-cancel-reply="${post.id}" type="button">Cancelar</button><button class="learning-submit-reply" data-submit-reply="${post.id}" type="button">Responder</button></div></div>` : ""}${post.replies.map((reply) => `<div class="learning-reply-item"><b>${esc(reply.name)}</b><span>${esc(reply.text)}</span></div>`).join("")}</article>`).join("") : `<div class="learning-empty-v3"><strong>Todavía no hay publicaciones</strong><span>Sé el primero en iniciar una conversación.</span><button id="emptyNewPostButton" class="learning-outline-v3" type="button">Nueva Publicación</button></div>`;
  }
  function modal() {
    if ($("#newPostModal")) return;
    const node = document.createElement("div"); node.id = "newPostModal"; node.className = "learning-modal-backdrop-v3"; node.innerHTML = `<div class="learning-modal-v3" role="dialog" aria-modal="true"><button class="learning-modal-close" data-close-modal type="button">×</button><span class="learning-eyebrow">COMUNIDAD PANASONIC</span><h2>Nueva Publicación</h2><label>Título<input id="postTitleInput" placeholder="Escribe el título de tu publicación" /></label><label>Contenido<textarea id="postContentInput" placeholder="Comparte una pregunta, experiencia o consejo..."></textarea></label><p id="postFormError" class="learning-form-error"></p><div class="learning-modal-actions"><button data-close-modal class="learning-cancel-v3" type="button">Cancelar</button><button id="publishPostButton" class="learning-primary-v3" type="button">Publicar</button></div></div>`; document.body.appendChild(node);
  }
  function setup() {
    renderPosts();
    const bell = $("#notifyBellBtn");
    if (bell) { bell.addEventListener("click", (event) => { event.stopImmediatePropagation(); let d = $("#notificationDropdown"); if (d) { d.remove(); return; } d = document.createElement("div"); d.id = "notificationDropdown"; d.className = "notification-dropdown-v3"; d.innerHTML = `<strong>Notificaciones</strong><button type="button"><b>Nueva capacitación disponible</b><span>Se ha agregado un nuevo curso de producto.</span></button><button type="button"><b>Curso completado</b><span>Has completado TV Basics.</span></button><button type="button"><b>Nuevo anuncio</b><span>Consulta las últimas novedades de productos.</span></button>`; document.body.appendChild(d); }); }
    document.addEventListener("click", (e) => { if (!e.target.closest("#notificationDropdown") && !e.target.closest("#notifyBellBtn")) $("#notificationDropdown")?.remove(); });
    $("#newPostButton")?.addEventListener("click", modal); $("#viewAllPostsButton")?.addEventListener("click", () => { document.querySelector(".learning-community-column")?.scrollIntoView({ behavior: "smooth", block: "center" }); toast("Mostrando todas las publicaciones"); });
    $("#postList")?.addEventListener("click", (e) => { const reply = e.target.closest("[data-reply]"); const cancel = e.target.closest("[data-cancel-reply]"); const submit = e.target.closest("[data-submit-reply]"); if (reply) { activeReply = Number(reply.dataset.reply); renderPosts(); } if (cancel) { activeReply = null; renderPosts(); } if (submit) { const post = posts.find((p) => p.id === Number(submit.dataset.submitReply)); const input = $(`[data-reply-input="${submit.dataset.submitReply}"]`); if (!input.value.trim()) return; post.replies.push({ name: "María González", text: input.value.trim() }); activeReply = null; renderPosts(); toast("Respuesta enviada correctamente"); } });
    document.addEventListener("click", (e) => { if (e.target.closest("#emptyNewPostButton")) modal(); if (e.target.closest("[data-close-modal]")) $("#newPostModal")?.remove(); if (e.target.closest("#publishPostButton")) { const title = $("#postTitleInput")?.value.trim(); const content = $("#postContentInput")?.value.trim(); if (!title || !content) { $("#postFormError").textContent = "Completa todos los campos."; return; } posts.unshift({ id: Date.now(), name: "María González", initials: "MG", time: "Ahora", title: `${title}: ${content}`, category: "Consultas Generales", replies: [] }); $("#newPostModal")?.remove(); renderPosts(); toast("Publicación creada correctamente"); } });
    const search = $("#learningSearchForm"); search?.addEventListener("submit", (e) => { e.preventDefault(); const q = $("#learningSearchInput").value.trim().toLowerCase(); const cards = [...document.querySelectorAll("#specializationGrid .specialization-card")]; let count = 0; cards.forEach((card) => { const match = !q || card.textContent.toLowerCase().includes(q); card.hidden = !match; if (match) count++; }); $("#learningSearchEmpty").hidden = count > 0; $("#learningSearchResults").hidden = count > 0; if (!count) toast("No se encontraron cursos"); });
    document.addEventListener("click", (e) => { const card = e.target.closest(".specialization-card"); if (!card) return; const title = card.querySelector(".specialization-step"); if (title) title.textContent = title.textContent.replace(/^\d+\.\s*/, ""); const badge = card.querySelector(".specialization-badge"); if (badge) badge.textContent = badge.textContent.includes("COMPLETADO") ? "Completado" : "No Iniciado"; });
  }
  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", setup); else setup();
})();
